[package]
name = "rust-code-challenges"
version = "0.1.0"
authors = ["Leonardo Viana Teixeira <leo.mec.eng18.com>"]
edition = "2018"

[lib]
name = "challenges_lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
